name: 
mode: "dev"
port: 
version: "v0.0.1"
start_time: "2022-08-27"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 
  port: 
  user: 
  password: 
  dbname: 
  max_open_conns: 
  max_idle_conns: 
redis:
  host: 
  port: 
  password: ""
  db: 6
  pool_size: 100
