name: "webProject"
mode: "dev"
port: 8084
version: "v0.0.1"
start_time: "2022-08-27"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 123.56.101.219
  port: 3306
  user: "root"
  password: "jxlJXL1112"
  dbname: "webProject"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 123.56.101.219
  port: jxlJXL1112
  password: ""
  db: 6
  pool_size: 100